// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB8mg_ecJsH_D2rwxkhMAoi_0RQYgJxlc',
    appId: '1:496672463796:web:481b8800878b19b24370e1',
    messagingSenderId: '496672463796',
    projectId: 'mallnavigate',
    authDomain: 'mallnavigate.firebaseapp.com',
    databaseURL: 'https://mallnavigate-default-rtdb.firebaseio.com',
    storageBucket: 'mallnavigate.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1uLbdSinbeODyR5EFc-Tyc7yr3pyXqtI',
    appId: '1:496672463796:android:da3af4701b5ecc404370e1',
    messagingSenderId: '496672463796',
    projectId: 'mallnavigate',
    databaseURL: 'https://mallnavigate-default-rtdb.firebaseio.com',
    storageBucket: 'mallnavigate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADGyQH7HePDwIgT6LTp7wxdQEYBpftZRE',
    appId: '1:496672463796:ios:dbf97c50ac6692a04370e1',
    messagingSenderId: '496672463796',
    projectId: 'mallnavigate',
    databaseURL: 'https://mallnavigate-default-rtdb.firebaseio.com',
    storageBucket: 'mallnavigate.appspot.com',
    iosClientId: '496672463796-ea0nm5sdg8citnpm4t4gn5e5q7de3a48.apps.googleusercontent.com',
    iosBundleId: 'com.example.mallsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADGyQH7HePDwIgT6LTp7wxdQEYBpftZRE',
    appId: '1:496672463796:ios:dbf97c50ac6692a04370e1',
    messagingSenderId: '496672463796',
    projectId: 'mallnavigate',
    databaseURL: 'https://mallnavigate-default-rtdb.firebaseio.com',
    storageBucket: 'mallnavigate.appspot.com',
    iosClientId: '496672463796-ea0nm5sdg8citnpm4t4gn5e5q7de3a48.apps.googleusercontent.com',
    iosBundleId: 'com.example.mallsystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB8mg_ecJsH_D2rwxkhMAoi_0RQYgJxlc',
    appId: '1:496672463796:web:52f1c57d4beec8ad4370e1',
    messagingSenderId: '496672463796',
    projectId: 'mallnavigate',
    authDomain: 'mallnavigate.firebaseapp.com',
    databaseURL: 'https://mallnavigate-default-rtdb.firebaseio.com',
    storageBucket: 'mallnavigate.appspot.com',
  );
}
